In [1]:
import pandas as pd
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
attakDF = pd.read_csv('completeAttackDataset/part-00000-e6662c78-2efd-429f-b2f4-b5d6cc536f5b-c000.csv')

/Users/gauravvashisth/anaconda3/envs/envtf/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [8]:
s =pd.isnull(attakDF).any(axis=1)

In [24]:
attakDF.columns[attakDF.isna().any()].tolist()

[]

In [23]:
attakDF[attakDF['Flow Bytes/s'].isna()==True]['Flow Bytes/s']

Series([], Name: Flow Bytes/s, dtype: object)

In [20]:
attakDF['Flow Bytes/s'].unique()

array(['0', '52830.18868', '33.91001554', ..., '17.42910952',
       '17.22344647', '18.05124749'], dtype=object)

In [22]:
attakDF['Flow Bytes/s'].fillna(0,inplace=True)

In [4]:
import pickle
with open('labelDict.bin','rb') as fout:
    dd = pickle.load(fout)

featureList =[x for sublist in list(dd.values())  for x in sublist]

colList= list(set(featureList))

In [5]:
len(colList)

22

In [30]:
dd.keys()

dict_keys(['DoS slowloris', 'SSH-Patator', 'DoS Slowhttp', 'FTP-Patator', 'Heartbleed', 'Web Attack', 'DoS Hulk', 'Infiltration', 'Bot', 'DDoS', 'PortScan', 'DoS GoldenEye'])

In [6]:
df = attakDF[colList]
#df['Label'] = attakDF.Label

In [36]:
df_label = pd.get_dummies(attakDF.Label)

In [39]:
len(list(condf.columns))

36

In [40]:
len(list(df_label.columns))

14

In [25]:
X_train, X_validtest, y_train, y_validtest = train_test_split(df, attakDF['Label'], test_size=0.20, random_state=42,stratify=attakDF['Label'])
X_valid, X_test, y_valid, y_test = train_test_split(X_validtest, y_validtest, test_size=0.50, random_state=42,stratify=y_validtest)



In [27]:
y_valid.groupby(y_valid).count() #y_train.groupby().count()

Label
Bot                           197
DDoS                         4183
DoS GoldenEye                1029
DoS Hulk                    23107
DoS Slowhttptest              550
DoS slowloris                 579
FTP-Patator                   794
Heartbleed                      1
Infiltration                    4
PortScan                    15893
SSH-Patator                   590
Web Attack-Brute Force        151
Web Attack-Sql Injection        2
Web Attack-XSS                 65
Name: Label, dtype: int64

In [19]:
y_train.describe()

count       424308
unique          14
top       DoS Hulk
freq        207966
Name: Label, dtype: object

In [26]:
y_test.groupby(y_test).count()

Label
Bot                           196
DDoS                         4184
DoS GoldenEye                1030
DoS Hulk                    23108
DoS Slowhttptest              550
DoS slowloris                 580
FTP-Patator                   794
Heartbleed                      1
Infiltration                    3
PortScan                    15893
SSH-Patator                   590
Web Attack-Brute Force        150
Web Attack-Sql Injection        2
Web Attack-XSS                 65
Name: Label, dtype: int64

In [28]:

sm = SMOTE(random_state=12, ratio = 1.0)
x_res, y_res = sm.fit_sample(X_train, y_train)

/Users/gauravvashisth/anaconda3/envs/envtf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function _ratio_float is deprecated; Use a float for 'ratio' is deprecated from version 0.2. The support will be removed in 0.4. Use a dict, str, or a callable instead.
  warnings.warn(msg, category=DeprecationWarning)


In [30]:
print(x_res.shape,y_res.shape)

(2588012, 22) (2588012,)


In [9]:
pd.get_dummies(y_res).values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=uint8)

In [10]:
attakDF['Label'].unique()

array(['FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'DoS Hulk', 'DoS GoldenEye', 'Heartbleed',
       'Web Attack-Brute Force', 'Web Attack-XSS',
       'Web Attack-Sql Injection', 'Infiltration', 'DDoS', 'PortScan',
       'Bot'], dtype=object)

In [31]:
np.savetxt('multiclass-tensor/stratified/X_train.np',x_res)
np.savetxt('multiclass-tensor/stratified/y_train.np',pd.get_dummies(y_res).values)
np.savetxt('multiclass-tensor/stratified/X_test.np',X_test.values)
np.savetxt('multiclass-tensor/stratified/y_test.np',pd.get_dummies(y_test).values)
np.savetxt('multiclass-tensor/stratified/X_valid.np',X_valid.values)
np.savetxt('multiclass-tensor/stratified/y_valid.np',pd.get_dummies(y_valid).values)


In [2]:
x_train = np.loadtxt('multiclass-tensor/newdata/X-train.np')
y_train = np.loadtxt('multiclass-tensor/newdata/y-train.np')


In [5]:
x_train[0,:]

array([  0.00000000e+00,   4.20000000e+01,   0.00000000e+00,
         2.92000000e+04,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         4.20000000e+01,   0.00000000e+00,   2.38095238e+04,
         0.00000000e+00,   1.00000000e+00,   4.20000000e+01,
         3.00000000e+00,   0.00000000e+00,   2.38095238e+04,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00])

In [6]:
y_train[0,:]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [8]:
y_train[2,:]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [15]:
ll = list(np.argmax(y_train[0:50,:],axis=1))

In [22]:
ll[:25]

[9, 3, 9, 3, 3, 1, 9, 3, 1, 3, 3, 3, 9, 9, 9, 9, 1, 3, 9, 3, 9, 1, 3, 3, 1]

In [39]:
x_dumm = x_train[:50,:]

In [36]:
x_dumm.shape

(5, 22)

In [40]:
y_dumm =y_train[:50]

In [33]:
list(np.argmax(y_dumm,axis=1))

[9,
 3,
 9,
 3,
 3,
 1,
 9,
 3,
 1,
 3,
 3,
 3,
 9,
 9,
 9,
 9,
 1,
 3,
 9,
 3,
 9,
 1,
 3,
 3,
 1,
 3,
 1,
 3,
 9,
 3]

In [41]:
np.savetxt('multiclass-tensor/newdata/X_dumm.np',x_dumm)
np.savetxt('multiclass-tensor/newdata/y_dumm.np',y_dumm)